#!/usr/bin/env python3
"""Embed the web fonts into every page as base64, so the toolbox makes no
third-party requests at all.

Two reasons this is worth the page weight:
  * privacy — loading fonts from a CDN hands every visitor's IP to Google
  * longevity — the goal is "still opens in ten years", and that rules out
    depending on someone else's URL staying alive

Archivo and IBM Plex Sans are variable fonts: one file covers every weight we
ask for. Faces are therefore grouped by file content and emitted with a
font-weight *range*, which keeps three copies of the same 40 KB out of the page.

Embedding is redistribution, so fonts/OFL-*.txt travel with the fonts and the
README names them. Do not remove those files.

Usage
  python3 build-fonts.py            rebuild the pages from the local .woff2
  python3 build-fonts.py --fetch    re-download the .woff2 from Google first
"""

import base64
import hashlib
import json
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
INDEX = os.path.join(HERE, 'faces.json')

PAGES = [os.path.join(ROOT, 'index.html'),
         os.path.join(ROOT, 'zine-fold', 'index.html'),
         os.path.join(ROOT, 'id-photo-sheet', 'index.html')]

CSS_URL = ('https://fonts.googleapis.com/css2'
           '?family=Archivo:wght@500;600;700'
           '&family=IBM+Plex+Mono:wght@400;500'
           '&family=IBM+Plex+Sans:wght@400;500;600'
           '&display=swap')

# A browser UA, or Google serves the legacy truetype CSS instead of woff2.
UA = ('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0 Safari/537.36')

# The interface is Chinese, but Archivo and IBM Plex carry no CJK — those
# glyphs come from the system stack in --font-*. So the Latin subset is the
# whole of what these files are ever asked to draw.
LATIN = 'U+0000-00FF'

BEGIN = '<!-- fonts:begin (generated by fonts/build-fonts.py — do not edit by hand) -->'
END = '<!-- fonts:end -->'


def get(url):
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    return urllib.request.urlopen(req).read()


def fetch():
    """Download the Latin faces, collapse duplicates, and write faces.json."""
    css = get(CSS_URL).decode('utf-8')
    groups = {}
    for body in re.findall(r'@font-face\s*\{(.*?)\}', css, re.S):
        if LATIN not in body:
            continue
        family = re.search(r"font-family:\s*'([^']+)'", body).group(1)
        weight = int(re.search(r'font-weight:\s*(\d+)', body).group(1))
        url = re.search(r'url\(([^)]+)\)', body).group(1)
        blob = groups.get(url, {}).get('blob') or get(url)
        g = groups.setdefault(url, {'blob': blob, 'family': family, 'weights': []})
        g['weights'].append(weight)

    for f in os.listdir(HERE):
        if f.endswith('.woff2'):
            os.remove(os.path.join(HERE, f))

    faces = []
    for g in groups.values():
        lo, hi = min(g['weights']), max(g['weights'])
        stem = g['family'].lower().replace(' ', '-')
        name = '%s-%d.woff2' % (stem, lo) if lo == hi else '%s-%d-%d.woff2' % (stem, lo, hi)
        with open(os.path.join(HERE, name), 'wb') as fh:
            fh.write(g['blob'])
        faces.append({'family': g['family'], 'weight': str(lo) if lo == hi else '%d %d' % (lo, hi),
                      'file': name, 'sha256': hashlib.sha256(g['blob']).hexdigest()})
        print('fetched %-30s %6.1f KB  weight %s' % (name, len(g['blob']) / 1024.0, faces[-1]['weight']))

    faces.sort(key=lambda f: (f['family'], f['file']))
    with open(INDEX, 'w', encoding='utf-8') as fh:
        json.dump(faces, fh, indent=2, ensure_ascii=False)
        fh.write('\n')


def block():
    faces = json.load(open(INDEX, encoding='utf-8'))
    out = [BEGIN, '<style>']
    total = 0
    for f in faces:
        blob = open(os.path.join(HERE, f['file']), 'rb').read()
        got = hashlib.sha256(blob).hexdigest()
        assert got == f['sha256'], '%s does not match faces.json — re-run with --fetch' % f['file']
        total += len(blob)
        out.append('@font-face{font-family:"%s";font-style:normal;font-weight:%s;'
                   'font-display:swap;src:url(data:font/woff2;base64,%s) format("woff2")}'
                   % (f['family'], f['weight'], base64.b64encode(blob).decode('ascii')))
    out += ['</style>', END]
    print('embedded %d faces, %.1f KB of font data' % (len(faces), total / 1024.0))
    return '\n'.join(out)


def main():
    if '--fetch' in sys.argv:
        fetch()
    new = block()
    for page in PAGES:
        html = open(page, encoding='utf-8').read()
        assert BEGIN in html and END in html, 'missing fonts markers in ' + page
        start, stop = html.index(BEGIN), html.index(END) + len(END)
        open(page, 'w', encoding='utf-8').write(html[:start] + new + html[stop:])
        print('wrote', os.path.relpath(page, ROOT))


if __name__ == '__main__':
    main()
